# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iOSExercise' do

pod 'AFNetworking'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'MBProgressHUD'

end

target 'iOSExerciseTests' do

end

